export type AsmaName = {
  index: number;
  arabic: string;
  meaning: string;
};

export const ASMA_NAMES: AsmaName[] = [
  { index: 1, arabic: "الرَّحْمَنُ", meaning: "اللي رحمته وسعت كل حاجة" },
  { index: 2, arabic: "الرَّحِيمُ", meaning: "اللي بيرحم المؤمنين دايماً" },
  { index: 3, arabic: "الْمَلِكُ", meaning: "صاحب الملك كله" },
  { index: 4, arabic: "الْقُدُّوسُ", meaning: "المنزّه عن أي عيب" },
  { index: 5, arabic: "السَّلَامُ", meaning: "اللي يعطي السلام والأمان" },
  { index: 6, arabic: "الْمُؤْمِنُ", meaning: "اللي بيأمّن خلقه" },
  { index: 7, arabic: "الْمُهَيْمِنُ", meaning: "الرقيب على كل شيء" },
  { index: 8, arabic: "الْعَزِيزُ", meaning: "القوي اللي ما يُغلب" },
  { index: 9, arabic: "الْجَبَّارُ", meaning: "اللي بيجبر القلوب المكسورة" },
  { index: 10, arabic: "الْمُتَكَبِّرُ", meaning: "صاحب الكبرياء وحده" },
  { index: 11, arabic: "الْخَالِقُ", meaning: "اللي خلق كل حاجة" },
  { index: 12, arabic: "الْبَارِئُ", meaning: "اللي بيبدع في خلقه" },
  { index: 13, arabic: "الْمُصَوِّرُ", meaning: "اللي صور كل مخلوق" },
  { index: 14, arabic: "الْغَفَّارُ", meaning: "بيغفر الذنوب كلها" },
  { index: 15, arabic: "الْقَهَّارُ", meaning: "القاهر فوق كل شيء" },
  { index: 16, arabic: "الْوَهَّابُ", meaning: "اللي بيدّي بغير حساب" },
  { index: 17, arabic: "الرَّزَّاقُ", meaning: "اللي بيرزق كل المخلوقات" },
  { index: 18, arabic: "الْفَتَّاحُ", meaning: "اللي بيفتح أبواب الخير" },
  { index: 19, arabic: "الْعَلِيمُ", meaning: "اللي بيعرف كل حاجة" },
  { index: 20, arabic: "الْقَابِضُ", meaning: "بيمسك الأرزاق بحكمته" },
  { index: 21, arabic: "الْبَاسِطُ", meaning: "بيوسّع على عباده" },
  { index: 22, arabic: "الْخَافِضُ", meaning: "اللي بيخفض المتكبرين" },
  { index: 23, arabic: "الرَّافِعُ", meaning: "بيرفع المؤمنين" },
  { index: 24, arabic: "الْمُعِزُّ", meaning: "اللي بيعزّ من يشاء" },
  { index: 25, arabic: "الْمُذِلُّ", meaning: "بيُذلّ المتكبرين" },
  { index: 26, arabic: "السَّمِيعُ", meaning: "اللي بيسمع كل حاجة" },
  { index: 27, arabic: "الْبَصِيرُ", meaning: "اللي بيشوف كل حاجة" },
  { index: 28, arabic: "الْحَكَمُ", meaning: "العادل في حكمه" },
  { index: 29, arabic: "الْعَدْلُ", meaning: "اللي ما يظلم أبداً" },
  { index: 30, arabic: "اللَّطِيفُ", meaning: "بيلطف بعباده" },
  { index: 31, arabic: "الْخَبِيرُ", meaning: "العارف بكل خفية" },
  { index: 32, arabic: "الْحَلِيمُ", meaning: "اللي بيصبر على عباده" },
  { index: 33, arabic: "الْعَظِيمُ", meaning: "صاحب العظمة" },
  { index: 34, arabic: "الْغَفُورُ", meaning: "اللي مغفرته واسعة" },
  { index: 35, arabic: "الشَّكُورُ", meaning: "بيشكر العمل القليل بأجر كبير" },
  { index: 36, arabic: "الْعَلِيُّ", meaning: "اللي علا فوق كل شيء" },
  { index: 37, arabic: "الْكَبِيرُ", meaning: "أكبر من كل حاجة" },
  { index: 38, arabic: "الْحَفِيظُ", meaning: "اللي بيحفظ كل شيء" },
  { index: 39, arabic: "الْمُقِيتُ", meaning: "اللي بيدبّر الأقوات" },
  { index: 40, arabic: "الْحَسِيبُ", meaning: "الكافي عباده" },
  { index: 41, arabic: "الْجَلِيلُ", meaning: "صاحب الجلال" },
  { index: 42, arabic: "الْكَرِيمُ", meaning: "كرمه ما له حدود" },
  { index: 43, arabic: "الرَّقِيبُ", meaning: "بيراقب كل حاجة" },
  { index: 44, arabic: "الْمُجِيبُ", meaning: "بيجيب الدعاء" },
  { index: 45, arabic: "الْوَاسِعُ", meaning: "علمه ورحمته واسعة" },
  { index: 46, arabic: "الْحَكِيمُ", meaning: "بيتصرف بحكمة" },
  { index: 47, arabic: "الْوَدُودُ", meaning: "بيحب عباده الصالحين" },
  { index: 48, arabic: "الْمَجِيدُ", meaning: "صاحب المجد" },
  { index: 49, arabic: "الْبَاعِثُ", meaning: "اللي بيبعث الناس يوم القيامة" },
  { index: 50, arabic: "الشَّهِيدُ", meaning: "بيشهد على كل حاجة" },
  { index: 51, arabic: "الْحَقُّ", meaning: "الموجود بالحق" },
  { index: 52, arabic: "الْوَكِيلُ", meaning: "اللي نتوكل عليه" },
  { index: 53, arabic: "الْقَوِيُّ", meaning: "صاحب القوة المطلقة" },
  { index: 54, arabic: "الْمَتِينُ", meaning: "الشديد اللي ما يضعف" },
  { index: 55, arabic: "الْوَلِيُّ", meaning: "ولي المؤمنين" },
  { index: 56, arabic: "الْحَمِيدُ", meaning: "المستحق للحمد كله" },
  { index: 57, arabic: "الْمُحْصِي", meaning: "اللي بيعد كل حاجة" },
  { index: 58, arabic: "الْمُبْدِئُ", meaning: "اللي بدأ الخلق" },
  { index: 59, arabic: "الْمُعِيدُ", meaning: "بيعيد الخلق بعد الموت" },
  { index: 60, arabic: "الْمُحْيِي", meaning: "اللي بيحيي الموتى" },
  { index: 61, arabic: "الْمُمِيتُ", meaning: "اللي بيتوفّى الأنفس" },
  { index: 62, arabic: "الْحَيُّ", meaning: "الحي اللي ما يموت" },
  { index: 63, arabic: "الْقَيُّومُ", meaning: "القائم على كل شيء" },
  { index: 64, arabic: "الْوَاجِدُ", meaning: "اللي ما يحتاج لحاجة" },
  { index: 65, arabic: "الْمَاجِدُ", meaning: "صاحب المجد والكرم" },
  { index: 66, arabic: "الْوَاحِدُ", meaning: "الواحد اللي ما له شريك" },
  { index: 67, arabic: "الْأَحَدُ", meaning: "الأحد الفرد" },
  { index: 68, arabic: "الصَّمَدُ", meaning: "اللي تلجأ إليه الخلائق" },
  { index: 69, arabic: "الْقَادِرُ", meaning: "القادر على كل شيء" },
  { index: 70, arabic: "الْمُقْتَدِرُ", meaning: "صاحب القدرة الكاملة" },
  { index: 71, arabic: "الْمُقَدِّمُ", meaning: "بيقدّم من يشاء" },
  { index: 72, arabic: "الْمُؤَخِّرُ", meaning: "بيؤخّر من يشاء" },
  { index: 73, arabic: "الْأَوَّلُ", meaning: "اللي قبل كل حاجة" },
  { index: 74, arabic: "الْآخِرُ", meaning: "اللي بعد كل حاجة" },
  { index: 75, arabic: "الظَّاهِرُ", meaning: "الواضح بآياته" },
  { index: 76, arabic: "الْبَاطِنُ", meaning: "اللي ما تدركه الحواس" },
  { index: 77, arabic: "الْوَالِي", meaning: "المالك المتصرف" },
  { index: 78, arabic: "الْمُتَعَالِي", meaning: "العالي عن كل نقص" },
  { index: 79, arabic: "الْبَرُّ", meaning: "صاحب البر والإحسان" },
  { index: 80, arabic: "التَّوَّابُ", meaning: "بيقبل التوبة" },
  { index: 81, arabic: "الْمُنْتَقِمُ", meaning: "بينتقم من الظالمين" },
  { index: 82, arabic: "الْعَفُوُّ", meaning: "بيعفو عن الذنوب" },
  { index: 83, arabic: "الرَّءُوفُ", meaning: "صاحب الرأفة" },
  { index: 84, arabic: "مَالِكُ الْمُلْكِ", meaning: "اللي بيدّي الملك ويأخذه" },
  { index: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", meaning: "صاحب الجلال والكرم" },
  { index: 86, arabic: "الْمُقْسِطُ", meaning: "العادل في حكمه" },
  { index: 87, arabic: "الْجَامِعُ", meaning: "بيجمع الناس يوم القيامة" },
  { index: 88, arabic: "الْغَنِيُّ", meaning: "اللي ما يحتاج لحد" },
  { index: 89, arabic: "الْمُغْنِي", meaning: "بيغني من يشاء" },
  { index: 90, arabic: "الْمَانِعُ", meaning: "بيمنع الضر" },
  { index: 91, arabic: "الضَّارُّ", meaning: "بيقدّر الضر بحكمته" },
  { index: 92, arabic: "النَّافِعُ", meaning: "بيقدّر النفع" },
  { index: 93, arabic: "النُّورُ", meaning: "نور السماوات والأرض" },
  { index: 94, arabic: "الْهَادِي", meaning: "بيهدي عباده" },
  { index: 95, arabic: "الْبَدِيعُ", meaning: "اللي ابتدع الخلق بلا مثال" },
  { index: 96, arabic: "الْبَاقِي", meaning: "اللي ما يفنى" },
  { index: 97, arabic: "الْوَارِثُ", meaning: "اللي يرث كل شيء" },
  { index: 98, arabic: "الرَّشِيدُ", meaning: "صاحب الرشد" },
  { index: 99, arabic: "الصَّبُورُ", meaning: "اللي ما يعجل بالعقوبة" },
];

export function getTodayName(): AsmaName {
  const day = Math.floor(Date.now() / (1000 * 60 * 60 * 24));
  return ASMA_NAMES[day % ASMA_NAMES.length];
}
